export component Wave inherits Rectangle {
    Path {
        fill: #4b242a;
        property<int> amplitude: 15;
        viewbox-width: 100;
        viewbox-height: 20;
        MoveTo {
            x: 100;
            y: 0;
        }
        LineTo {
            x: 100;
            y: amplitude;
        }
        LineTo {
            x: 0;
            y: amplitude;
        }
        LineTo {
            x: 0;
            y: 0;
        }
        QuadraticTo {
            control-y: -amplitude * Math.cos(animation-tick() / 1s * 70deg);
            control-x: 25;
            x: 50;
            y: 0;
        }
        QuadraticTo {
            control-y: amplitude * Math.cos(animation-tick() / 1s * 70deg);
            control-x: 75;
            x: 100;
            y: 0;
        }
    }
    Rectangle {
        background: #4b242a;
        height: parent.height;
        y: parent.height / 2;
    }
}
 
