import { SpinBox } from "../../widgets/spinbox.slint";
import { Palette } from "palette.slint";
import { GlobalState, GlobalCallbacks } from "../../globals.slint";

export component SettingsView inherits Rectangle {
    // This thing shouldn't let clicks through
    TouchArea {}
    property<length> font-size: 42px;
    GridLayout {
        spacing: 12px;
        padding: 18px;
        Row {
            Text {
                text: "Work minutes";
                font-size: font-size;
                wrap: word-wrap;
            }
            SpinBox {
                background: Palette.background_dark;
                value: GlobalState.settings.pomodoro_duration / 60s;
                font-size: font-size;
                min: 1;
                max: 99;
                changed => {
                    GlobalState.settings.pomodoro_duration = self.value * 60s;
                    GlobalCallbacks.settings_update();
                }
            }
        }
        Row {
            Text {
                text: "Rest minutes";
                font-size: font-size;
                wrap: word-wrap;
            }
            SpinBox {
                background: Palette.background_dark;
                value: GlobalState.settings.short_break_duration / 60s;
                font-size: font-size;
                min: 1;
                max: 99;
                changed => {
                    GlobalState.settings.short_break_duration = self.value * 60s;
                    GlobalCallbacks.settings_update();
                }
            }
        }
        Row {
            Text {
                text: "Long rest minutes";
                font-size: font-size;
                wrap: word-wrap;
            }
            SpinBox {
                background: Palette.background_dark;
                value: GlobalState.settings.long_break_duration / 60s;
                font-size: font-size;
                min: 1;
                max: 99;
                changed => {
                    GlobalState.settings.long_break_duration = self.value * 60s;
                    GlobalCallbacks.settings_update();
                }
            }
        }
        Row {
            Text {
                text: "Rounds";
                font-size: font-size;
                wrap: word-wrap;
            }
            spinbox := SpinBox {
                max: 20;
                min: 1;
                font-size: font-size;
                background: Palette.background_dark;
                value: GlobalState.settings.pomodoros_in_cycle;
                changed => {
                    GlobalState.settings.pomodoros_in_cycle = self.value;
                    GlobalCallbacks.settings_update();
                }
            }
        }
        Row {
            Text {
                text: "Sound volume (%)";
                font-size: font-size;
                wrap: word-wrap;
            }
            SpinBox {
                max: 200;
                min: 0;
                font-size: font-size;
                background: Palette.background_dark;
                value: GlobalState.settings.sound_volume;
                width: spinbox.width;
                changed => {
                    GlobalState.settings.sound_volume = self.value;
                    GlobalCallbacks.settings_update();
                }
            }
        }
    }
}
