
import { Segment } from "segment.slint";

export component SevenSegment {
    in property<int> upscaling_factor: 1;
    width: upscaling_factor * 11px;
    height: upscaling_factor * 24px;

    in property<int> digit: 0;
    property<[bool]> activated_segments: calculate_segments(digit);

    function calculate_segments(digit: int) -> [bool] {
        if (digit == 0) {
            return [true, true, false, true, true, true, true];
        } else if (digit == 1) {
            return [false, false, false, true, false, false, true];
        } else if (digit == 2) {
            return [true, false, true, true, true, true, false];
        } else if (digit == 3) {
            return [true, false, true, true, false, true, true];
        } else if (digit == 4) {
            return [false, true, true, true, false, false, true];
        } else if (digit == 5) {
            return [true, true, true, false, false, true, true];
        } else if (digit == 6) {
            return [true, true, true, false, true, true, true];
        } else if (digit == 7) {
            return [true, false, false, true, false, false, true];
        } else if (digit == 8) {
            return [true, true, true, true, true, true, true];
        } else if (digit == 9) {
            return [true, true, true, true, false, true, true];
        } 
        return [false, false, false, false, false, false, false];
    }

    seg0 := Segment {
        y: 0;
        upscaling_factor: upscaling_factor;
        movable_part: @image-url("images/segments/0_movable.png");
        stationary_part: @image-url("images/segments/0_stationary.png");
        active: activated_segments[0];
    }
    seg1 := Segment {
        x: 0;
        y: 1px * upscaling_factor;
        upscaling_factor: upscaling_factor;
        movable_part: @image-url("images/segments/1_movable.png");
        stationary_part: @image-url("images/segments/1_stationary.png");
        active: activated_segments[1];
    }
    seg3 := Segment {
        x: parent.width - self.width;
        y: 1px * upscaling_factor;
        upscaling_factor: upscaling_factor;
        movable_part: @image-url("images/segments/3_movable.png");
        stationary_part: @image-url("images/segments/3_stationary.png");
        active: activated_segments[3];
    }
    seg2 := Segment {
        upscaling_factor: upscaling_factor;
        movable_part: @image-url("images/segments/2_movable.png");
        stationary_part: @image-url("images/segments/2_stationary.png");
        active: activated_segments[2];
    }
    seg4 := Segment {
        x: 0;
        y: parent.height - self.height - 1px * upscaling_factor;
        upscaling_factor: upscaling_factor;
        movable_part: @image-url("images/segments/4_movable.png");
        stationary_part: @image-url("images/segments/4_stationary.png");
        active: activated_segments[4];
    }
    seg6 := Segment {
        x: parent.width - self.width;
        y: parent.height - self.height - 1px * upscaling_factor;
        upscaling_factor: upscaling_factor;
        movable_part: @image-url("images/segments/6_movable.png");
        stationary_part: @image-url("images/segments/6_stationary.png");
        active: activated_segments[6];
    }
    seg5 := Segment {
        y: parent.height - self.height;
        upscaling_factor: upscaling_factor;
        movable_part: @image-url("images/segments/5_movable.png");
        stationary_part: @image-url("images/segments/5_stationary.png");
        active: activated_segments[5];
    }
}

